apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
